const data = {
    products:[
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews:10,
            description: 'High Quality Product',
        },
        {
            _id:'2',
            name: 'Addidas',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4,
            numReviews:100,
            description: 'High Quality Product',
        },
        {
            _id:'3',
            name: 'Free Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Lacoste',
            rating: 5,
            numReviews:17,
            description: 'High Quality Product',
        },
        {
            _id:'4',
            name: 'Cool Boy Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 70,
            brand: 'Nike',
            rating: 3,
            numReviews:17,
            description: 'High Quality Product',
        },
        {
            _id:'5',
            name: 'Big Boy',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 80,
            brand: 'Nike',
            rating: 1,
            numReviews:20,
            description: 'High Quality Product',
        },
        {
            _id:'6',
            name: 'Nike fits Shirt',
            category: 'Shirts',
            image:'/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 5,
            numReviews:10,
            description: 'High Quality Product',
        },
    ]
}
export default data;